gems: [jekyll-paginate, jekyll-gist]
markdown:    kramdown
#highlighter: rouge

timezone: Europe/Berlin

title: Alinex

paginate:    5
paginate_path: "blog/page:num"

collections:
  develop:
    output: true

kramdown:
  fenced_code_blocks: true
